// src/extensions/events.ts —— P3 Task 19：25 条「支持」事件的**载荷类型**（pi 同名同形，逐字转写）。
//
// 出处：pi-coding-agent@1.0.0 `dist/core/extensions/types.d.ts`。为什么需要这个文件：
// 换注入模型后事件载荷**不再由 pi-agent-core 投递**，而是由浏览器宿主构造后交给 `runner.emit()`
// （spec R6 / D4）。载荷形状因此成为「宿主 ↔ 扩展」之间的契约面，本文件就是那份契约。
//
// 纪律：
//   ① **逐字转写，不发明**。每段都带上游 `文件:行` 出处；`test/extensions-events-types.test.ts`
//      用 tsc 直接把本文件的类型与上游 `types.d.ts`（相对路径 import devDep）做双向 assignability
//      对照，转写漂了会在 tsc 上红——不靠人眼核对。
//   ② 上游从 `@earendil-works/pi-ai` / `pi-agent-core` import 的类型**照旧 import**（同一份东西，
//      不复制第二份）；只在 CLI 仓内部（`session-manager` / `compaction` / `system-prompt` / `messages`）
//      且本仓兑现不了其实现的那几个类型上做转写，并在每处注明出处。
//   ③ 只转写 25 条「支持」事件的**可达闭包**。`contract.ts` 标 UNSUPPORTED 的事件（ui_* /
//      input / user_bash / resources_discover / project_trust / session_before_switch|…）**不转写**——
//      不为不支持的公开面准备类型（声明了却不生效比不声明更糟，spec §3.2 口径）。
//   ④ `powershell` 工具事件保留在上游联合里（联合逐字照抄），但本仓不实现该工具（`contract.ts`
//      的 `EXTENSION_API_MEMBERS` 无同名物）；它只是联合的一个分支，不构成公开承诺。
import type { AgentMessage, ThinkingLevel } from '@earendil-works/pi-agent-core';
import type {
	AssistantMessage, AssistantMessageEvent, ImageContent, JsonValue, Message, Model,
	ProviderHeaders, SystemMessage, TextContent, ToolResultMessage, Usage, UserMessage,
} from '@earendil-works/pi-ai';
// 工具入参/详情类型复用本仓 P2 工具件的同名导出（上游从 `../tools/index.ts` 聚合，本仓没有那层 barrel，
// 按模块逐个 import；形状由 `test/extensions-events-types.test.ts` 的对照断言钉住）
import type { BashToolDetails, BashToolInput } from '../tools/bash-tool';
import type { EditToolDetails, EditToolInput } from '../tools/edit-tool';
import type { FindToolDetails, FindToolInput } from '../tools/find-tool';
import type { GrepToolDetails, GrepToolInput } from '../tools/grep-tool';
import type { LsToolDetails, LsToolInput } from '../tools/ls-tool';
import type { ReadToolDetails, ReadToolInput } from '../tools/read-tool';
import type { WriteToolInput } from '../tools/write-tool';
import type { Skill } from '../skills/loader';

// ———— CLI 仓内部类型的逐字转写（出处逐条注明）———

/** 出处：`core/messages.ts:32`。`custom` 角色的消息（扩展注入 LLM 上下文用）。 */
export interface CustomMessage<T = unknown> {
	role: 'custom';
	customType: string;
	content: string | (TextContent | ImageContent)[];
	display: boolean;
	details?: T;
	timestamp: number;
}

/** 出处：`core/session-manager.d.ts:17`。 */
export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

/** 出处：`core/session-manager.d.ts:23`。 */
export interface SessionMessageEntry extends SessionEntryBase {
	type: 'message';
	message: AgentMessage;
}

/** 出处：`core/session-manager.d.ts:27`。 */
export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: 'thinking_level_change';
	thinkingLevel: string;
}

/** 出处：`core/session-manager.d.ts:31`。 */
export interface ModelChangeEntry extends SessionEntryBase {
	type: 'model_change';
	provider: string;
	modelId: string;
}

/** 出处：`core/session-manager.d.ts:36`。 */
export interface UsageEntry extends SessionEntryBase {
	type: 'usage';
	/** Arbitrary usage category, such as "cache_warm". */
	kind: string;
	provider: string;
	model: string;
	usage: Usage;
	/** Optional human-readable qualifier for usage notices. */
	note?: string;
}

/** 出处：`core/session-manager.d.ts:46`。 */
export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: 'compaction';
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** Usage from the LLM call(s) that generated this summary, if available */
	usage?: Usage;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromHook?: boolean;
	/** Complete prompt and tool state at this compaction boundary. */
	systemMessage?: SystemMessage;
}

/** 出处：`core/session-manager.d.ts:60`。 */
export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: 'branch_summary';
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** Usage from the LLM call that generated this summary, if available */
	usage?: Usage;
	/** True if generated by an extension, false if pi-generated */
	fromHook?: boolean;
}

/** 出处：`core/session-manager.d.ts:81`。 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: 'custom';
	customType: string;
	data?: T;
}

/** 出处：`core/session-manager.d.ts:87`。 */
export interface LabelEntry extends SessionEntryBase {
	type: 'label';
	targetId: string;
	label: string | undefined;
}

/** 出处：`core/session-manager.d.ts:93`。 */
export interface SessionInfoEntry extends SessionEntryBase {
	type: 'session_info';
	name?: string;
}

/** 出处：`core/session-manager.d.ts:109`。 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: 'custom_message';
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
}

/** 出处：`core/session-manager.d.ts:117`。 */
export type ContextEditableContent = UserMessage['content'] | AssistantMessage['content'] | ToolResultMessage['content'] | CustomMessage['content'];

/** 出处：`core/session-manager.d.ts:119`。 */
export interface ContextEditEntry extends SessionEntryBase {
	type: 'context_edit';
	targetId: string;
	/** Null omits the target from model context. A value replaces only its content. */
	replacement: { content: ContextEditableContent } | null;
}

/** 出处：`core/session-manager.d.ts:128`。 */
export type SessionEntry =
	| SessionMessageEntry | ThinkingLevelChangeEntry | ModelChangeEntry | UsageEntry
	| CompactionEntry | BranchSummaryEntry | CustomEntry | CustomMessageEntry
	| ContextEditEntry | LabelEntry | SessionInfoEntry;

/** 出处：`core/session-manager.d.ts:140`。 */
export interface ProjectedSessionEntry {
	/** Raw append-only entry that owns this projected contribution. */
	sourceEntry: SessionEntry;
	/** Model-visible messages after context edits. Empty for state-only entries and omissions. */
	messages: AgentMessage[];
}

/** 出处：`core/compaction/compaction.d.ts:18`。 */
export interface CompactionResult<T = unknown> {
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	estimatedTokensAfter?: number;
	/** Usage from the LLM call(s) that generated this summary, if available */
	usage?: Usage;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
}

/** 出处：`core/compaction/compaction.d.ts:28`。 */
export interface CompactionSettings {
	enabled: boolean;
	reserveTokens: number;
	keepRecentTokens: number;
}

/** 出处：`core/compaction/utils.d.ts:6`。 */
export interface FileOperations {
	read: Set<string>;
	written: Set<string>;
	edited: Set<string>;
}

/** 出处：`core/compaction/compaction.d.ts:118`。 */
export interface CompactionPreparation {
	/** UUID of first entry to keep */
	firstKeptEntryId: string;
	/** Messages that will be summarized and discarded */
	messagesToSummarize: AgentMessage[];
	/** Messages that will be turned into turn prefix summary (if splitting) */
	turnPrefixMessages: AgentMessage[];
	/** Whether this is a split turn (cut point in middle of turn) */
	isSplitTurn: boolean;
	tokensBefore: number;
	/** Summary from previous compaction, for iterative update */
	previousSummary?: string;
	/** File operations extracted from messagesToSummarize */
	fileOps: FileOperations;
	/** Compaction settions from settings.jsonl\t*/
	settings: CompactionSettings;
}

/** 出处：`core/system-prompt.d.ts:5`。 */
export interface BuildSystemPromptOptions {
	/** Custom system prompt (replaces the default prefix). */
	customPrompt?: string;
	/** Exact full prompt replacement set by a before_agent_start handler. */
	forceSystemPrompt?: string;
	/** Tools to include in prompt. Default: [read, bash, edit, write]. */
	selectedTools?: string[];
	/** Optional one-line tool snippets keyed by tool name. */
	toolSnippets?: Record<string, string>;
	/** Guideline bullets contributed by each tool, keyed by tool name. */
	toolGuidelines?: Record<string, string[]>;
	/** Additional guideline bullets appended to the default system prompt rules. */
	promptGuidelines?: string[];
	/** Text appended from user configuration before project context, skills, and cwd. */
	appendSystemPrompt?: string;
	/** Additional XML-wrapped prompt sections keyed by tag name. */
	sections?: Record<string, string>;
	/** Working directory. */
	cwd: string;
	/** Pre-loaded context files. */
	contextFiles?: Array<{ path: string; content: string }>;
	/** Pre-loaded skills. */
	skills?: Skill[];
}

/** 出处：`core/system-prompt.d.ts:32`。 */
export type NormalizedBuildSystemPromptOptions = BuildSystemPromptOptions & {
	selectedTools: string[];
	toolSnippets: Record<string, string>;
	toolGuidelines: Record<string, string[]>;
	promptGuidelines: string[];
	appendSystemPrompt: string;
	sections: Record<string, string>;
	contextFiles: Array<{ path: string; content: string }>;
	skills: Skill[];
};

/** 出处：`core/extensions/types.d.ts:616`。 */
export interface TreePreparation {
	targetId: string;
	oldLeafId: string | null;
	commonAncestorId: string | null;
	entriesToSummarize: SessionEntry[];
	userWantsSummary: boolean;
	/** Custom instructions for summarization */
	customInstructions?: string;
	/** If true, customInstructions replaces the default prompt instead of being appended */
	replaceInstructions?: boolean;
	/** Label to attach to the branch summary entry */
	label?: string;
}

// ———— 25 条「支持」事件的载荷（`types.d.ts` 逐字）———

/** 出处：`types.d.ts:547`。 */
export interface SessionStartEvent {
	type: 'session_start';
	/** Why this session start happened. */
	reason: 'startup' | 'reload' | 'new' | 'resume' | 'fork';
	/** Previously active session file. Present for "new", "resume", and "fork". */
	previousSessionFile?: string;
}

/** 出处：`types.d.ts:609`。 */
export interface SessionShutdownEvent {
	type: 'session_shutdown';
	reason: 'quit' | 'reload' | 'new' | 'resume' | 'fork';
	/** Destination session file when shutting down due to session replacement. */
	targetSessionFile?: string;
}

/** 出处：`types.d.ts:573`。 */
export interface SessionBeforeCompactEvent {
	type: 'session_before_compact';
	preparation: CompactionPreparation;
	branchEntries: SessionEntry[];
	customInstructions?: string;
	/** What triggered the compaction: manual /compact, the context threshold, or context overflow recovery */
	reason: 'manual' | 'threshold' | 'overflow';
	/** True when the aborted turn is retried after this compaction (overflow recovery) */
	willRetry: boolean;
	signal: AbortSignal;
}

/** 出处：`types.d.ts:585`。 */
export interface SessionCompactEvent {
	type: 'session_compact';
	compactionEntry: CompactionEntry;
	fromExtension: boolean;
	/** What triggered the compaction: manual /compact, the context threshold, or context overflow recovery */
	reason: 'manual' | 'threshold' | 'overflow';
	/** True when the aborted turn is retried after this compaction (overflow recovery) */
	willRetry: boolean;
}

/** 出处：`types.d.ts:630`。 */
export interface SessionBeforeTreeEvent {
	type: 'session_before_tree';
	preparation: TreePreparation;
	signal: AbortSignal;
}

/** 出处：`types.d.ts:636`。 */
export interface SessionTreeEvent {
	type: 'session_tree';
	newLeafId: string | null;
	oldLeafId: string | null;
	summaryEntry?: BranchSummaryEntry;
	fromExtension?: boolean;
}

/** 出处：`types.d.ts:651`。 */
export interface ContextEvent {
	type: 'context';
	messages: AgentMessage[];
}

/** 出处：`types.d.ts:665`。 */
export interface BeforeProviderRequestEvent {
	type: 'before_provider_request';
	payload: unknown;
}

/** 出处：`types.d.ts:674`。 */
export interface BeforeProviderHeadersEvent {
	type: 'before_provider_headers';
	headers: ProviderHeaders;
}

/** 出处：`types.d.ts:679`。 */
export interface AfterProviderResponseEvent {
	type: 'after_provider_response';
	status: number;
	headers: Record<string, string>;
}

/** 出处：`types.d.ts:693`。 */
export interface BeforeAgentStartEvent {
	type: 'before_agent_start';
	/** The raw user prompt text (after expansion). */
	prompt: string;
	/** Images attached to the user prompt, if any. */
	images?: ImageContent[];
	/** The current system prompt, rendered from systemPromptOptions and earlier handler changes. */
	readonly systemPrompt: string;
	/** Mutable prompt sections. Later handlers observe mutations made by earlier handlers. */
	systemPromptOptions: NormalizedBuildSystemPromptOptions;
}

/** 出处：`types.d.ts:705`。 */
export interface AgentStartEvent {
	type: 'agent_start';
}

/** 出处：`types.d.ts:709`。 */
export interface AgentEndEvent {
	type: 'agent_end';
	messages: AgentMessage[];
}

/** 出处：`types.d.ts:781`。 */
export interface TurnStartEvent {
	type: 'turn_start';
	turnIndex: number;
	timestamp: number;
}

/** 出处：`types.d.ts:703`。 */
export type AgentActivityOutcome = 'completed' | 'aborted' | 'error';

/** 出处：`types.d.ts:705`（`CustomEntryDraft`）。 */
export interface CustomEntryDraft {
	type: 'custom';
	customType: string;
	data?: unknown;
}

/** 出处：`types.d.ts:712`（`CustomMessageEntryDraft`）。 */
export interface CustomMessageEntryDraft {
	type: 'custom_message';
	customType: string;
	content: string | (TextContent | ImageContent)[];
	display: boolean;
	details?: unknown;
}

/** 出处：`types.d.ts:719`（`ContextEditEntryDraft`）。 */
export interface ContextEditEntryDraft {
	type: 'context_edit';
	targetId: string;
	replacement: ContextEditEntry['replacement'];
}

/** 出处：`types.d.ts:725`（`CompactionEntryDraft`）。 */
export interface CompactionEntryDraft {
	type: 'compaction';
	summary: string;
	/** Null creates a self-retaining compaction that keeps no preceding entries. */
	firstKeptEntryId: string | null;
	details?: unknown;
	usage?: Usage;
}

/** 出处：`types.d.ts:731`。 */
export type SessionBoundaryDraft = CustomEntryDraft | CustomMessageEntryDraft | ContextEditEntryDraft | CompactionEntryDraft;

/** 出处：`types.d.ts:732`。 */
export interface BoundaryContextPreview {
	contextEntries: ProjectedSessionEntry[];
	contextMessages: AgentMessage[];
	llmMessages: Message[];
	pendingMessages: AgentMessage[];
	canContinue: boolean;
}

/** 出处：`types.d.ts:739`。 */
export interface BoundaryState {
	entries: SessionBoundaryDraft[];
	continue: boolean;
	context: BoundaryContextPreview;
	outcome: AgentActivityOutcome;
}

/** 出处：`types.d.ts:746`。 */
export interface BoundaryResult {
	entries?: SessionBoundaryDraft[];
	continue?: boolean;
}

/** 出处：`types.d.ts:787`。 */
export interface TurnEndEvent extends BoundaryState {
	type: 'turn_end';
	turnIndex: number;
	message: AgentMessage;
	toolResults: ToolResultMessage[];
	messageEntryId: string;
	toolResultEntryIds: string[];
}

/** 出处：`types.d.ts:796`。 */
export interface MessageStartEvent {
	type: 'message_start';
	message: AgentMessage;
}

/** 出处：`types.d.ts:801`。 */
export interface MessageUpdateEvent {
	type: 'message_update';
	message: AgentMessage;
	assistantMessageEvent: AssistantMessageEvent;
}

/** 出处：`types.d.ts:807`。 */
export interface MessageEndEvent {
	type: 'message_end';
	message: AgentMessage;
}

/** 出处：`types.d.ts:812`。 */
export interface ToolExecutionStartEvent {
	type: 'tool_execution_start';
	toolCallId: string;
	toolName: string;
	args: any;
	/** Set when another tool (for example a codemode script) made this call. */
	parentToolCallId?: string;
}

/** 出处：`types.d.ts:821`。 */
export interface ToolExecutionUpdateEvent {
	type: 'tool_execution_update';
	toolCallId: string;
	toolName: string;
	args: any;
	partialResult: any;
	/** Set when another tool (for example a codemode script) made this call. */
	parentToolCallId?: string;
}

/** 出处：`types.d.ts:831`。 */
export interface ToolExecutionEndEvent {
	type: 'tool_execution_end';
	toolCallId: string;
	toolName: string;
	result: any;
	isError: boolean;
	/** Set when another tool (for example a codemode script) made this call. */
	parentToolCallId?: string;
}

/** 出处：`types.d.ts:840`。 */
export type ModelSelectSource = 'set' | 'cycle' | 'restore';

/** 出处：`types.d.ts:842`。 */
export interface ModelSelectEvent {
	type: 'model_select';
	model: Model<any>;
	previousModel: Model<any> | undefined;
	source: ModelSelectSource;
}

/** 出处：`types.d.ts:849`。 */
export interface ThinkingLevelSelectEvent {
	type: 'thinking_level_select';
	level: ThinkingLevel;
	previousLevel: ThinkingLevel;
}

// ———— 工具事件：9 个内置变体 + custom 兜底（`types.d.ts:888-996`）———

/** 出处：`types.d.ts:888`。 */
interface ToolCallEventBase {
	type: 'tool_call';
	/**
	 * The call's id. For calls another tool made (with `parentToolCallId` set), pi assigns
	 * `<parent id>/<n>`; such ids never appear as tool calls or tool results in the transcript, only
	 * in the parent result's `nestedCalls` record.
	 */
	toolCallId: string;
	/** Set when another tool (for example a codemode script) issued this call. */
	parentToolCallId?: string;
}

export interface BashToolCallEvent extends ToolCallEventBase { toolName: 'bash'; input: BashToolInput }
/** 上游 `PowerShellToolCallEvent`；`PowerShellToolInput = BashToolInput`（`tools/powershell.d.ts:10`）。 */
export interface PowerShellToolCallEvent extends ToolCallEventBase { toolName: 'powershell'; input: BashToolInput }
export interface ReadToolCallEvent extends ToolCallEventBase { toolName: 'read'; input: ReadToolInput }
export interface EditToolCallEvent extends ToolCallEventBase { toolName: 'edit'; input: EditToolInput }
export interface WriteToolCallEvent extends ToolCallEventBase { toolName: 'write'; input: WriteToolInput }
export interface GrepToolCallEvent extends ToolCallEventBase { toolName: 'grep'; input: GrepToolInput }
export interface FindToolCallEvent extends ToolCallEventBase { toolName: 'find'; input: FindToolInput }
export interface LsToolCallEvent extends ToolCallEventBase { toolName: 'ls'; input: LsToolInput }
export interface CustomToolCallEvent extends ToolCallEventBase { toolName: string; input: Record<string, unknown> }

/** 出处：`types.d.ts:941`。 */
export type ToolCallEvent =
	| BashToolCallEvent | PowerShellToolCallEvent | ReadToolCallEvent | EditToolCallEvent
	| WriteToolCallEvent | GrepToolCallEvent | FindToolCallEvent | LsToolCallEvent | CustomToolCallEvent;

/** 出处：`types.d.ts:944`。 */
interface ToolResultEventBase {
	type: 'tool_result';
	/** The call's id; `<parent id>/<n>` for nested calls, see `ToolCallEvent`. */
	toolCallId: string;
	/** Set when another tool (for example a codemode script) issued this call. */
	parentToolCallId?: string;
	input: Record<string, unknown>;
	content: (TextContent | ImageContent)[];
	/**
	 * Machine-readable result for tools that declare an `outputSchema`. Handlers that redact
	 * `content` should also replace this; replacing `content` alone drops it.
	 */
	structuredContent?: JsonValue;
	isError: boolean;
	/** Usage from the tool execution itself, if available. */
	usage?: Usage;
}

export interface BashToolResultEvent extends ToolResultEventBase { toolName: 'bash'; details: BashToolDetails | undefined }
/** 上游 `PowerShellToolResultEvent`；`PowerShellToolDetails = BashToolDetails`（`tools/powershell.d.ts`）。 */
export interface PowerShellToolResultEvent extends ToolResultEventBase { toolName: 'powershell'; details: BashToolDetails | undefined }
export interface ReadToolResultEvent extends ToolResultEventBase { toolName: 'read'; details: ReadToolDetails | undefined }
export interface EditToolResultEvent extends ToolResultEventBase { toolName: 'edit'; details: EditToolDetails | undefined }
/** 出处：`types.d.ts:975`——上游 `WriteToolDetails` 就是 `undefined`。 */
export interface WriteToolResultEvent extends ToolResultEventBase { toolName: 'write'; details: undefined }
export interface GrepToolResultEvent extends ToolResultEventBase { toolName: 'grep'; details: GrepToolDetails | undefined }
export interface FindToolResultEvent extends ToolResultEventBase { toolName: 'find'; details: FindToolDetails | undefined }
export interface LsToolResultEvent extends ToolResultEventBase { toolName: 'ls'; details: LsToolDetails | undefined }
export interface CustomToolResultEvent extends ToolResultEventBase { toolName: string; details: unknown }

/** 出处：`types.d.ts:996`。 */
export type ToolResultEvent =
	| BashToolResultEvent | PowerShellToolResultEvent | ReadToolResultEvent | EditToolResultEvent
	| WriteToolResultEvent | GrepToolResultEvent | FindToolResultEvent | LsToolResultEvent | CustomToolResultEvent;

// ———— handler 返回值类型（`types.d.ts` 逐字）———

/** 出处：`types.d.ts:1046`。 */
export interface ToolCallEventResult {
	/** Block tool execution. To modify arguments, mutate `event.input` in place instead. */
	block?: boolean;
	reason?: string;
	/**
	 * Hint that the agent should stop after the current tool batch when this call is blocked.
	 * Early termination only happens when every finalized tool result in the batch sets this to true.
	 */
	terminate?: boolean;
}

/** 出处：`types.d.ts:1071`。 */
export interface ToolResultEventResult {
	content?: (TextContent | ImageContent)[];
	details?: unknown;
	structuredContent?: JsonValue;
	isError?: boolean;
	usage?: Usage;
}

/** 出处：`types.d.ts:1078`。 */
export interface MessageEndEventResult {
	/** Replace the finalized message. The replacement must keep the original message role. */
	message?: AgentMessage;
}

/** 出处：`types.d.ts:1082`。 */
export interface BeforeAgentStartEventResult {
	message?: Pick<CustomMessage, 'customType' | 'content' | 'display' | 'details'>;
	/** Replace the complete system prompt for this turn. Later handlers observe this exact override. */
	systemPrompt?: string;
}

/** 出处：`types.d.ts:1094`。 */
export interface SessionBeforeCompactResult {
	cancel?: boolean;
	compaction?: CompactionResult;
}

/** 出处：`types.d.ts:1098`。 */
export interface SessionBeforeTreeResult {
	cancel?: boolean;
	summary?: { summary: string; details?: unknown; usage?: Usage };
}

/**
 * 25 条「支持」事件的联合（名单真源是 `contract.ts` 的 `SUPPORTED_EVENTS`；本类型只是它们的类型侧）。
 * 「支持」判定与名单**不**在这里做——那是 `contract.ts` 的职责，两边由
 * `test/extensions-contract.test.ts` 双向钉住（键集合必须逐字相等）。
 */
export type SupportedExtensionEvent =
	| SessionStartEvent | SessionBeforeCompactEvent | SessionCompactEvent | SessionShutdownEvent
	| SessionBeforeTreeEvent | SessionTreeEvent | ContextEvent | BeforeProviderRequestEvent
	| BeforeProviderHeadersEvent | AfterProviderResponseEvent | BeforeAgentStartEvent
	| AgentStartEvent | AgentEndEvent | TurnStartEvent | TurnEndEvent
	| MessageStartEvent | MessageUpdateEvent | MessageEndEvent
	| ToolExecutionStartEvent | ToolExecutionUpdateEvent | ToolExecutionEndEvent
	| ModelSelectEvent | ThinkingLevelSelectEvent | ToolCallEvent | ToolResultEvent;
